repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
  # no install
  #      - id: requirements-txt-fixer

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports
        exclude: __init__.py

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.1
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

# no install
#  - repo: https://github.com/asottile/setup-cfg-fmt
#    rev: v2.5.0
#    hooks:
#      - id: setup-cfg-fmt

# this is a leetcode repo - do we really need pyright?!?!
#  # from https://github.com/microsoft/pyright/blob/main/docs/ci-integration.md
#  - repo: local
#    hooks:
#      - id: pyright
#        name: pyright
#        entry: pyright
#        language: node
#        language_version: 14.15.3
#        pass_filenames: false
#        types: [ python ]
#        additional_dependencies: [ 'pyright@1.1.269' ]
